version: "3.1"

services:
  postgres:
    image: postgres:13.3
    container_name: user_pg
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54320:5432"   # Внешний порт 54320 -> внутренний 5432
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
